### ISSUE TITLE
Is there any way to use the option handle?

### ISSUE THREAD

**Issue by JRadagast** [t-k-f/vue-packery-draggabilly-plugin#1]
I have tried looking into this, but haven't managed to do it.

It still drags regardless of where I drag on the whole object i'm trying to move, when it should only drag when I click on a specific part of the draggable object.

**Comment by jan-thoma** [comment]
This plugin will no longer be maintained for alternative see [vue-binpacker-plugin](https://github.com/t-k-f/vue-binpacker-plugin).

**Comment by ssuess** [comment]
@JRadagast FYI if you go into the build.js file and change `new _draggabilly2.default(a)` to `new _draggabilly2.default(a,{handle: '.handle'})` it will work (assuming you are using `handle` as your class)
