### ISSUE TITLE
Possible to store the order choices?

### ISSUE THREAD

**Issue by ssuess** [t-k-f/vue-packery-draggabilly-plugin#2]
When dragging items, is there any callback mechanism to store the order that an item was dragged to?

**Comment by TobiTenno** [comment]
this would be excellent to be able to provide a vuex store to save them to and sync to

**Comment by ssuess** [comment]
still would LOVE this feature...

**Comment by jan-thoma** [comment]
This plugin will no longer be maintained for alternative see [vue-binpacker-plugin](https://github.com/t-k-f/vue-binpacker-plugin).
