### ISSUE TITLE
npm run babel with any change at all breaks plugin

### ISSUE THREAD

**Issue by ssuess** [t-k-f/vue-packery-draggabilly-plugin#5]
Hi, I know that this is deprecated, but while we are awaiting your new plugin, I was hoping to make a small change to allow handle grabbing. But it seems as if any change at all I make to your plugin (followed by `npm run babel`) breaks it. Is there some trick to re-compiling after making a change? Here were my steps:

1. Change line 16 from `el.draggie = new Draggabilly(el)` to `el.draggie = new Draggabilly(el, { handle: '.handle' })`
2. npm run babel

and the errors I get after that are: `draggie is not defined`
( btw if I run the `npm run babel` command after making a change on the parent plugin, it works just fine)

Any suggestions? Thanks!

**Comment by ssuess** [comment]
Well, I found a workaround by manually editing the original build file. It seems that the babel build process introduces some odd changes that break the plugin. By comparing my babel build with yours, I was able to just add the code I needed directly to the build.js file. Ugly process, but it works.

**Comment by jan-thoma** [comment]
This plugin is no longer maintained, in consideration that packery doesn't play very nice with Vue. Development of a "native" bin packer will continue here => [vue-binpacker-plugin](https://github.com/t-k-f/vue-binpacker-plugin).
